"""Add updated_at to Sheet model

Revision ID: 5ba8c28af60b
Revises: a387e1deebec
Create Date: 2025-04-23 13:52:19.028019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '5ba8c28af60b'
down_revision = 'a387e1deebec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('data',
               existing_type=sqlite.JSON(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheet', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
